server:
  address: 0.0.0.0
  port: 8099

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true 
    serialization: 
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty 

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.enable_lazy_load_no_trans: true
    jpa:
      repositories.enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    co.mega: DEBUG
  file: app.log

security:
  jwt:
    token:
      secret-key: MFivmer9Xj4z84z24Ds20f
      expire-length: 604800000

veh:
  log:
    url:
      prefix: http://marsops.i-tetris.com:8888/veh_log/
    path: /Users/zhouji/codes/ndata/api/src/test/log_data
